### ISSUE TITLE
in 2022.7 not working last working 2022.6.7

### ISSUE THREAD

**Issue by abcdeyka** [davidramosweb/home-assistant-custom-components-cover-time-based#15]
Logger: homeassistant.core
Source: custom_components/mega/tools.py:67
Integration: mega ([documentation](https://github.com/andvikt/mega_hacs), [issues](https://github.com/andvikt/mega_hacs/issues))
First occurred: 03:19:27 (2 occurrences)
Last logged: 03:19:33

Error executing service: <ServiceCall homeassistant.turn_on (c:01G7JQKD5FKY9M2HMN6NF3AF90): entity_id=['light.mega2_09']>
Error executing service: <ServiceCall homeassistant.turn_off (c:01G7JQKJNCR0TCFW41VA8PYMN8): entity_id=['light.mega2_09']>
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/core.py", line 1731, in catch_exceptions
await coro_or_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/usr/src/homeassistant/homeassistant/components/homeassistant/init.py", line 124, in async_handle_turn_service
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
await service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/light/init.py", line 553, in async_handle_light_on_service
await light.async_turn_on(filter_turn_on_params(light, params))
File "/config/custom_components/mega/entities.py", line 478, in async_turn_on
await self.mega.request(_cmd, priority=-1)
File "/config/custom_components/mega/hub.py", line 300, in request
async with self._http_lck(priority):
File "/usr/local/lib/python3.10/contextlib.py", line 199, in aenter
return await anext(self.gen)
File "/config/custom_components/mega/tools.py", line 47, in _with_priority
await self.acquire(p)
File "/config/custom_components/mega/tools.py", line 67, in acquire
fut = self._loop.create_future()
AttributeError: 'NoneType' object has no attribute 'create_future'

**Comment by B1n00** [comment]
I have the same issue as well. Any fix anticipated it seems related to python version.
